import { ArrowRight } from "lucide-react";

export const data = [
  {
    id: 1,
    option_a: "Remembering and Understanding",
    symbol: "→",
    option_b: "Dialogic Instructional Strategies",
    symbol2: "→",
    option_c: "Collaboration and Communication Tools",
  },
  {
    id: 2,
    option_a: "Remembering and Understanding",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Knowledge Representation Tools",
  },
  {
    id: 3,
    option_a: "Remembering and Understanding",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Content Creation Tools",
  },
  {
    id: 4,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Exploratory Instructional Strategies",
    symbol2: "→",
    option_c: "Immersive Technologies",
  },
  {
    id: 5,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Dialogic Instructional Strategies",
    symbol2: "→",
    option_c: "Collaboration and Communication Tools",
  },
  {
    id: 6,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Content Creation Tools",
  },
  {
    id: 7,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Knowledge Representation Tools",
  },
  {
    id: 8,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Information Search and Resource Management",
  },
  {
    id: 9,
    option_a: "Applying and Analyzing",
    symbol: "→",
    option_b: "Supportive Instructional Strategies",
    symbol2: "→",
    option_c: "Collaboration and Communication Tools",
  },
  {
    id: 10,
    option_a: "Evaluating and Creating",
    symbol: "→",
    option_b: "Exploratory Instructional Strategies",
    symbol2: "→",
    option_c: "Immersive Technologies",
  },
  {
    id: 11,
    option_a: "Evaluating and Creating",
    symbol: "→",
    option_b: "Exploratory Instructional Strategies",
    symbol2: "→",
    option_c: "Content Creation Tools",
  },
  {
    id: 12,
    option_a: "Evaluating and Creating",
    symbol: "→",
    option_b: "Dialogic Instructional Strategies",
    symbol2: "→",
    option_c: "Knowledge Representation Tools",
  },
  {
    id: 13,
    option_a: "Evaluating and Creating",
    symbol: "→",
    option_b: "Dialogic Instructional Strategies",
    symbol2: "→",
    option_c: "Collaboration and Communication Tools",
  },
];

export type Choice = (typeof data)[number];
